name: branches-feature
on:
  push:
    branches: feature/*
env:
  docker_username: "${{ secrets.docker_username }}"
  docker_password: "${{ secrets.docker_password }}"
jobs:
  step_job_1:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.1.0
    - name: Build microservices jar
      run: mvn package
    - uses: actions/upload-artifact@v4.1.0
      with:
        name: step_job_1
        path: target/**
  step_job_2:
    runs-on: ubuntu-latest
    environment:
      name: approval_required
    needs:
    - step_job_1
    steps:
    - uses: actions/checkout@v4.1.0
    - uses: actions/download-artifact@v4.1.0
      with:
        name: step_job_1
    - name: Analyze Java project with NG SAST
      run: sl analyze --app ${BITBUCKET_REPO_SLUG} --tag branch=${BITBUCKET_BRANCH} --java --cpg target/my-app.jar
