name: pull-requests-master
on:
  pull_request:
    branches: master
env:
  docker_username: "${{ secrets.docker_username }}"
  docker_password: "${{ secrets.docker_password }}"
jobs:
  step_job_1:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.1.0
    - name: Build microservices jar
      run: mvn package
    - name: Build React app
      run: |-
        yarn install
        yarn run build
    - uses: actions/upload-artifact@v4.1.0
      with:
        name: step_job_1
        path: target/**
  parallel_job_2:
    runs-on: ubuntu-latest
    needs:
    - step_job_1
    steps:
    - uses: actions/checkout@v4.1.0
    - uses: actions/download-artifact@v4.1.0
      with:
        name: step_job_1
    - name: Analyze Java project with NG SAST
      run: sl analyze --app ${BITBUCKET_REPO_SLUG} --tag branch=${BITBUCKET_BRANCH} --java --cpg target/my-app.jar
  parallel_job_3:
    runs-on: ubuntu-latest
    needs:
    - step_job_1
    steps:
    - uses: actions/checkout@v4.1.0
    - uses: actions/download-artifact@v4.1.0
      with:
        name: step_job_1
    - name: Analyze JS/TS project with NG SAST
      run: sl analyze --app ${BITBUCKET_REPO_SLUG} --tag branch=${BITBUCKET_BRANCH} --js --cpg . --ts --babel
